name: Deploy UserProfile to Dev
on:
  push:
    branches:
      - dev
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read

jobs:
  deploylearningcredentials:
    runs-on: windows-latest
    environment: dev

    name: 'Deploy UserProfile'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - uses: actions/checkout@v2

   
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Add Nuget source
        run: dotnet nuget add source 'https://pkgs.dev.azure.com/e-LfH/_packaging/LearningHubFeed/nuget/v3/index.json' --name 'LearningHubFeed'  --username 'colin.beeby' --password ${{ secrets.AZURE_DEVOPS_PAT }} --store-password-in-clear-text      
          
      - name: Extract version from tag
        id: vars
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          $TAG = git describe --tags --abbrev=0
          $VERSION = $TAG -replace '^v', ''
          echo "VERSION=$VERSION" >> $env:GITHUB_ENV

      - name: Update assembly version in .csproj
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          (Get-Content **/LearningHub.Nhs.UserProfileUI.csproj) -replace '<AssemblyVersion>.*</AssemblyVersion>', "<AssemblyVersion>${{ env.VERSION }}</AssemblyVersion>" | Set-Content **/LearningHub.Nhs.UserProfileUI.csproj
          (Get-Content **/LearningHub.Nhs.UserProfileUI.csproj) -replace '<FileVersion>.*</FileVersion>', "<FileVersion>${{ env.VERSION }}</FileVersion>" | Set-Content **/LearningHub.Nhs.UserProfileUI.csproj
          (Get-Content **/LearningHub.Nhs.UserProfileUI.csproj) -replace '<Version>.*</Version>', "<Version>${{ env.VERSION }}</Version>" | Set-Content **/LearningHub.Nhs.UserProfileUI.csproj
          
      - name: Show assembly version
        run: |
          (Get-Content **/LearningHub.Nhs.UserProfileUI.csproj | Select-String '<AssemblyVersion>') | Write-Host


      - name: dotnet build and publish
        run: |
          dotnet restore
          dotnet build --configuration Release

