name: Deploy UserProfile to Dev
on:
  push:
    branches:
      - dev
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read

jobs:
  deploylearningcredentials:
    runs-on: windows-latest
    environment: dev

    name: 'Deploy UserProfile'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - uses: actions/checkout@v2

   
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Add Nuget source
        run: dotnet nuget add source 'https://pkgs.dev.azure.com/e-LfH/_packaging/LearningHubFeed/nuget/v3/index.json' --name 'LearningHubFeed'  --username 'colin.beeby' --password ${{ secrets.AZURE_DEVOPS_PAT }} --store-password-in-clear-text      
          
          
      - name: Extract version from tag
        id: vars
        shell: bash 
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV

      - name: Update assembly version in .csproj
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          sed -i "s|<AssemblyVersion>.*</AssemblyVersion>|<AssemblyVersion>${{ env.VERSION }}</AssemblyVersion>|"  **/LearningHub.Nhs.UserProfileUI.csproj
          sed -i "s|<FileVersion>.*</FileVersion>|<FileVersion>${{ env.VERSION }}</FileVersion>|" **/LearningHub.Nhs.UserProfileUI.csproj
          sed -i "s|<Version>.*</Version>|<Version>${{ env.VERSION }}</Version>|" **/LearningHub.Nhs.UserProfileUI.csproj

      - name: dotnet build and publish
        run: |
          dotnet restore
          dotnet build --configuration Release

